version: '3.8'
services:
  db:
    image: postgres:15-alpine  # ou mysql:8.0
    environment:
      POSTGRES_DB: eco_garden
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
