blank_issues_enabled: false
issue_templates:
    - name: "Nouvelle fonctionnalité"
      description: "Proposer une nouvelle fonctionnalité pour EcoGarden API"
      title: "[Fonctionnalité]: "
      labels: ["amelioration"]
      body: "./ISSUE_TEMPLATE/feature_request.md"
